### PR TITLE
Front end with weight graph

### PR DESCRIPTION
**Pull request by anishan**
This change is [Reviewable](https://reviewable.io/reviews/shanekelly/smart-hive/1)

### CODE REVIEW

**Review by PrimePalaver — CHANGES_REQUESTED** [review]
FYI
I made a change on master so that Heroku would automatically deploy to the web for each PR. I had to rebase this branch on top of master in order for things to work, so you may have to `git fetch && git reset --hard origin/frontend`. Sorry about the weirdness...

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/shanekelly/smart-hive/1#-:-Ld5i-X_9qXNvIo6FdCg:b-87nj6b)* status: all files reviewed, 11 unresolved discussions (waiting on @anishan)

*[a discussion](https://reviewable.io/reviews/shanekelly/smart-hive/1#-Ld5qVqK6ZlKZKPDrLLd:-Ld5qVqK6ZlKZKPDrLLe:bbqkjxl) (no related file):*
This is so amazing!!! :100: :1st_place_medal: :100: 

---
___
*[app/routes.py, line 17 at r1](https://reviewable.io/reviews/shanekelly/smart-hive/1#-Ld5iZa_8rQHt7lSRn1z:-Ld5iZa_8rQHt7lSRn2-:bwy7fqc) ([raw file](https://github.com/shanekelly/smart-hive/blob/393932cac5bcbbe0794198ce23ba80b9b7974c07/app/routes.py#L17)):*
> ```Python
> #   for the secret MongoDB URI we use.
> mongo_uri = os.environ['MONGODB_URI']
> print(mongo_uri)
> ```

Do we still need to print the URI here?
___
*[app/routes.py, line 29 at r1](https://reviewable.io/reviews/shanekelly/smart-hive/1#-Ld5jHth5lSvAePTuRd_:-Ld5jHth5lSvAePTuRda:b4if2w2) ([raw file](https://github.com/shanekelly/smart-hive/blob/393932cac5bcbbe0794198ce23ba80b9b7974c07/app/routes.py#L29)):*
> ```Python
>   return render_template('home.html', entries=entries)
> 
> # send database information in GET request
> ```

Nit
Could you change this function-level comment to follow the PEP8 standard of using three double-quotes? Something like:
```
"""
Send database information in GET request.
"""
```
___
*[app/routes.py, line 37 at r1](https://reviewable.io/reviews/shanekelly/smart-hive/1#-Ld5k-LyCQ79WB4KTOZt:-Ld5k-LyCQ79WB4KTOZu:bn92e8z) ([raw file](https://github.com/shanekelly/smart-hive/blob/393932cac5bcbbe0794198ce23ba80b9b7974c07/app/routes.py#L37)):*
> ```Python
>     for entry in entries:
>         entry_json = {}
>         entry_json["id"] = str(entry.get("_id"))
> ```

Do you mean to assume the `dict.get()` default behavior of returning `None` if the specified key does not exist in the dictionary? I don't think there is a case where `_id` does not exist in an `entry`, but if it doesn't, then we probably want to throw an error.
Maybe use the `[]` operator, eg `entry['_id']`? This might also be the case with some of the `.get` calls below?
___
*[app/routes.py, line 37 at r1](https://reviewable.io/reviews/shanekelly/smart-hive/1#-Ld5kc-u1sKnvc0Bs2K8:-Ld5kc-u1sKnvc0Bs2K9:bgod1j8) ([raw file](https://github.com/shanekelly/smart-hive/blob/393932cac5bcbbe0794198ce23ba80b9b7974c07/app/routes.py#L37)):*
> ```Python
>     for entry in entries:
>         entry_json = {}
>         entry_json["id"] = str(entry.get("_id"))
> ```

Nit
The PEP8 standard for string literals is single quotes instead of double quotes. Could you replace all of your `"` with `'`?
___
*[app/routes.py, line 45 at r1](https://reviewable.io/reviews/shanekelly/smart-hive/1#-Ld5luE7D2Rt8lavkD29:-Ld5luE7D2Rt8lavkD2A:b-r45dlh) ([raw file](https://github.com/shanekelly/smart-hive/blob/393932cac5bcbbe0794198ce23ba80b9b7974c07/app/routes.py#L45)):*
> ```Python
>         slash_index = int(entry.get("topic").index('/'))
>         hive_name = topic[0:slash_index]
>         category = topic[slash_index+1:len(topic)]
> ```

I think you could achieve this a bit more pythonically with
```
hive_name, _, category = entry['topic'].partition('/')
```
https://docs.python.org/3/library/stdtypes.html#str.partition
___
*[app/static/index.js, line 1 at r1](https://reviewable.io/reviews/shanekelly/smart-hive/1#-Ld5omEF5lm5FK30Rkx_:-Ld5omEF5lm5FK30Rkxa:b5uynkm) ([raw file](https://github.com/shanekelly/smart-hive/blob/393932cac5bcbbe0794198ce23ba80b9b7974c07/app/static/index.js#L1)):*
> ```JavaScript
> GLOBAL = {}
> ```

What's this?
___
*[app/static/index.js, line 24 at r1](https://reviewable.io/reviews/shanekelly/smart-hive/1#-Ld5oL6QDpU6gJOYBtcD:-Ld5oL6QDpU6gJOYBtcE:b-3altr9) ([raw file](https://github.com/shanekelly/smart-hive/blob/393932cac5bcbbe0794198ce23ba80b9b7974c07/app/static/index.js#L24)):*
> ```JavaScript
> window.addEventListener("resize", createWeightSVG);
> 
> function loadData() {
> ```

Could you add some function-level documentation for each of these functions? It would especially help me undestand things because I don't really know javascript stuff....
I always find myself looking at this for examples http://usejsdoc.org/about-getting-started.html
___
*[app/static/index.js, line 25 at r1](https://reviewable.io/reviews/shanekelly/smart-hive/1#-Ld5pK2V92MCrhdRt4Zo:-Ld5pK2V92MCrhdRt4Zp:b4p42l1) ([raw file](https://github.com/shanekelly/smart-hive/blob/393932cac5bcbbe0794198ce23ba80b9b7974c07/app/static/index.js#L25)):*
> ```JavaScript
> 
> function loadData() {
>   // console.log("load data");
> ```

Do you still need these commented out console logs?
___
*[app/static/index.js, line 220 at r1](https://reviewable.io/reviews/shanekelly/smart-hive/1#-Ld5pwhT6ZVK4iLMu1R8:-Ld5pwhT6ZVK4iLMu1R9:bnic52p) ([raw file](https://github.com/shanekelly/smart-hive/blob/393932cac5bcbbe0794198ce23ba80b9b7974c07/app/static/index.js#L220)):*
> ```JavaScript
> }
> 
> function map_range(value, low1, high1, low2, high2) {
> ```

Should this function be `mapRange`?
___
*[app/templates/home.html, line 8 at r1](https://reviewable.io/reviews/shanekelly/smart-hive/1#-Ld5qCQnC-JNPsuLj6rX:-Ld5qCQnC-JNPsuLj6rY:b-m8dtyw) ([raw file](https://github.com/shanekelly/smart-hive/blob/393932cac5bcbbe0794198ce23ba80b9b7974c07/app/templates/home.html#L8)):*
> ```HTML
>     <script src="https://d3js.org/d3.v5.min.js"></script>
>     <script src="{{url_for('static', filename='index.js')}}"></script>
>     
> ```

Do you still need this commented line?

**Review by anishan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/shanekelly/smart-hive/1)* status: 2 of 5 files reviewed, 10 unresolved discussions (waiting on @shanekelly)

*[a discussion](https://reviewable.io/reviews/shanekelly/smart-hive/1#-Ld5qVqK6ZlKZKPDrLLd:-LdBhliP5PZ_YV_paHzf:b32vjw) (no related file):*
<details><summary><i>Previously, shanekelly (Shane Kelly) wrote…</i></summary><blockquote>

This is so amazing!!! :100: :1st_place_medal: :100: 
</blockquote></details>

<3

---
___
*[app/routes.py, line 17 at r1](https://reviewable.io/reviews/shanekelly/smart-hive/1#-Ld5iZa_8rQHt7lSRn1z:-LdBrQH4CvFCdwmk0xyC:b-896fja) ([raw file](https://github.com/shanekelly/smart-hive/blob/393932cac5bcbbe0794198ce23ba80b9b7974c07/app/routes.py#L17)):*
<details><summary><i>Previously, shanekelly (Shane Kelly) wrote…</i></summary><blockquote>

Do we still need to print the URI here?
</blockquote></details>

Done!
___
*[app/routes.py, line 29 at r1](https://reviewable.io/reviews/shanekelly/smart-hive/1#-Ld5jHth5lSvAePTuRd_:-LdBrghM6NFQAuHMEGOR:b-896fja) ([raw file](https://github.com/shanekelly/smart-hive/blob/393932cac5bcbbe0794198ce23ba80b9b7974c07/app/routes.py#L29)):*
<details><summary><i>Previously, shanekelly (Shane Kelly) wrote…</i></summary><blockquote>

Nit
Could you change this function-level comment to follow the PEP8 standard of using three double-quotes? Something like:
```
"""
Send database information in GET request.
"""
```
</blockquote></details>

Done!
___
*[app/routes.py, line 37 at r1](https://reviewable.io/reviews/shanekelly/smart-hive/1#-Ld5k-LyCQ79WB4KTOZt:-LdBsmye1sY3m1RB7OZX:b-896fja) ([raw file](https://github.com/shanekelly/smart-hive/blob/393932cac5bcbbe0794198ce23ba80b9b7974c07/app/routes.py#L37)):*
<details><summary><i>Previously, shanekelly (Shane Kelly) wrote…</i></summary><blockquote>

Do you mean to assume the `dict.get()` default behavior of returning `None` if the specified key does not exist in the dictionary? I don't think there is a case where `_id` does not exist in an `entry`, but if it doesn't, then we probably want to throw an error.
Maybe use the `[]` operator, eg `entry['_id']`? This might also be the case with some of the `.get` calls below?
</blockquote></details>

Done!
___
*[app/routes.py, line 37 at r1](https://reviewable.io/reviews/shanekelly/smart-hive/1#-Ld5kc-u1sKnvc0Bs2K8:-LdBtCsK6J2HVX2t0qkM:bb7m07t) ([raw file](https://github.com/shanekelly/smart-hive/blob/393932cac5bcbbe0794198ce23ba80b9b7974c07/app/routes.py#L37)):*
<details><summary><i>Previously, shanekelly (Shane Kelly) wrote…</i></summary><blockquote>

Nit
The PEP8 standard for string literals is single quotes instead of double quotes. Could you replace all of your `"` with `'`?
</blockquote></details>

okay
___
*[app/routes.py, line 45 at r1](https://reviewable.io/reviews/shanekelly/smart-hive/1#-Ld5luE7D2Rt8lavkD29:-LdBtQko4AAbgDMP601K:b-896fix) ([raw file](https://github.com/shanekelly/smart-hive/blob/393932cac5bcbbe0794198ce23ba80b9b7974c07/app/routes.py#L45)):*
<details><summary><i>Previously, shanekelly (Shane Kelly) wrote…</i></summary><blockquote>

I think you could achieve this a bit more pythonically with
```
hive_name, _, category = entry['topic'].partition('/')
```
https://docs.python.org/3/library/stdtypes.html#str.partition
</blockquote></details>

Done.
___
*[app/static/index.js, line 1 at r1](https://reviewable.io/reviews/shanekelly/smart-hive/1#-Ld5omEF5lm5FK30Rkx_:-LdBtZ1jDUitBso9SDZP:b-p1i752) ([raw file](https://github.com/shanekelly/smart-hive/blob/393932cac5bcbbe0794198ce23ba80b9b7974c07/app/static/index.js#L1)):*
<details><summary><i>Previously, shanekelly (Shane Kelly) wrote…</i></summary><blockquote>

What's this?
</blockquote></details>

added comment
___
*[app/static/index.js, line 24 at r1](https://reviewable.io/reviews/shanekelly/smart-hive/1#-Ld5oL6QDpU6gJOYBtcD:-LdBumWnDo_FjdL8uSHI:b-896fix) ([raw file](https://github.com/shanekelly/smart-hive/blob/393932cac5bcbbe0794198ce23ba80b9b7974c07/app/static/index.js#L24)):*
<details><summary><i>Previously, shanekelly (Shane Kelly) wrote…</i></summary><blockquote>

Could you add some function-level documentation for each of these functions? It would especially help me undestand things because I don't really know javascript stuff....
I always find myself looking at this for examples http://usejsdoc.org/about-getting-started.html
</blockquote></details>

Done.
___
*[app/static/index.js, line 25 at r1](https://reviewable.io/reviews/shanekelly/smart-hive/1#-Ld5pK2V92MCrhdRt4Zo:-LdBthTI0LKnl0GQpDdJ:b2nhswy) ([raw file](https://github.com/shanekelly/smart-hive/blob/393932cac5bcbbe0794198ce23ba80b9b7974c07/app/static/index.js#L25)):*
<details><summary><i>Previously, shanekelly (Shane Kelly) wrote…</i></summary><blockquote>

Do you still need these commented out console logs?
</blockquote></details>

Yes
___
*[app/static/index.js, line 220 at r1](https://reviewable.io/reviews/shanekelly/smart-hive/1#-Ld5pwhT6ZVK4iLMu1R8:-LdBurLg-aDojT_WG3kf:b-896fix) ([raw file](https://github.com/shanekelly/smart-hive/blob/393932cac5bcbbe0794198ce23ba80b9b7974c07/app/static/index.js#L220)):*
<details><summary><i>Previously, shanekelly (Shane Kelly) wrote…</i></summary><blockquote>

Should this function be `mapRange`?
</blockquote></details>

Done.
___
*[app/templates/home.html, line 8 at r1](https://reviewable.io/reviews/shanekelly/smart-hive/1#-Ld5qCQnC-JNPsuLj6rX:-LdBvMCz-a9jAbjlDY-d:b-896fix) ([raw file](https://github.com/shanekelly/smart-hive/blob/393932cac5bcbbe0794198ce23ba80b9b7974c07/app/templates/home.html#L8)):*
<details><summary><i>Previously, shanekelly (Shane Kelly) wrote…</i></summary><blockquote>

Do you still need this commented line?
</blockquote></details>

Done.

**Review by PrimePalaver — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/shanekelly/smart-hive/1)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @anishan and @shanekelly)

___
*[app/routes.py, line 48 at r2](https://reviewable.io/reviews/shanekelly/smart-hive/1#-LdBxRzR3DlOR1cQRSvf:-LdBxRzR3DlOR1cQRSvg:b-ar4f8v) ([raw file](https://github.com/shanekelly/smart-hive/blob/68d669b1f401283175d409145a1e139541eaed02/app/routes.py#L48)):*
> ```Python
>         entries_list.append(entry_json)
>     entries_json = {}
>     entries_json["data"] = entries_list
> ```

`"` -> `'`
___
*[app/static/index.js, line 25 at r1](https://reviewable.io/reviews/shanekelly/smart-hive/1#-Ld5pK2V92MCrhdRt4Zo:-LdBxr5t7e8Wwyei9xe8:bqrdkgu) ([raw file](https://github.com/shanekelly/smart-hive/blob/393932cac5bcbbe0794198ce23ba80b9b7974c07/app/static/index.js#L25)):*
<details><summary><i>Previously, anishan (Anisha Nakagawa) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

:male_detective: 
___
*[app/static/index.js, line 9 at r2](https://reviewable.io/reviews/shanekelly/smart-hive/1#-LdBxjseDUdx8ONt0ezG:-LdBxjseDUdx8ONt0ezH:bkmnep2) ([raw file](https://github.com/shanekelly/smart-hive/blob/68d669b1f401283175d409145a1e139541eaed02/app/static/index.js#L9)):*
> ```JavaScript
> 
>   // set up toggling listeners
>   $('.collapsible').click(function(){
> ```

I don't know the convention off the top of my head, but I think you should use all `'` or all `"`.

**Review by PrimePalaver — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/shanekelly/smart-hive/1)* status: all files reviewed, 1 unresolved discussion (waiting on @anishan)

**Review by PrimePalaver — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/shanekelly/smart-hive/1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
